### ISSUE TITLE
Use of badly maintained snippet library

### ISSUE THREAD

**Issue by blyedev** [ironlungx/dotfiles#1]
I suggest deleting the friendly-snippet, snippet source in [here](https://github.com/ironlungx/dotfiles/blob/main/.config/nvim/lua/plugins/completions.lua). For newer languages they have badly maintained snippets often using out of date functions, syntax which are doubled in the lsp anyways making them nearly obsolete

**Comment by ironlungx** [comment]
🤭🤭🤭🤭🤭🤭🤭🤭🤭. I removed it, need to push now!

**Comment by ironlungx** [comment]
fixed with commit c37ef23a1d860264aa2b6941e73f13a21139eb26
