### ISSUE TITLE
[Enhancment] A better completion box formatter

### ISSUE THREAD

**Issue by blyedev** [ironlungx/dotfiles#2]
I suggest you use the "onsails/lspkind.nvim". It allows you to see the source of each completion which would have allowed you to avoid #1. 

Get the plugin [here](https://github.com/onsails/lspkind.nvim)

Here's [my config](https://github.com/blyedev/nvim-config/blob/28b73127b12f8e805c8d9ce375b37b9de7b56232/lua/plugins/completion.lua) of it for reference

**Comment by ironlungx** [comment]
I think i have it installed, I just haven't configured it to show the source *yet*. Should I use icons or text for the source?

**Comment by blyedev** [comment]
Yup, i mean that's up to preference I am just a huge fan of square brackets as special text

**Comment by ironlungx** [comment]
okay i did that then!
